site_name: PACKAGE_NAME

repo_url: https://github.com/dawsonbooth/REPO_NAME/
site_url: https://dawsonbooth.github.io/REPO_NAME/

theme:
  name: material
  palette:
    primary: black
    accent: red

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: True

nav:
  - Overview: README.md
  - API Reference: api.md
