site_name: ascii-art-cli

repo_url: https://github.com/dawsonbooth/ascii-art/
site_url: https://dawsonbooth.github.io/ascii-art/

theme:
  name: material
  palette:
    primary: black
    accent: red

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: True

nav:
  - Overview: README.md
  - API Reference: api.md
