site_name: PACKAGE_NAME

repo_url: https://github.com/dawsonbooth/PACKAGE_NAME/
site_url: https://dawsonbooth.github.io/PACKAGE_NAME/

theme:
  name: material
  palette:
    primary: black
    accent: red

nav:
  - Overview: README.md
  - API Reference: api.md
