[tool.poetry]
name = "PACKAGE_NAME"
version = "0.0.1"
description = ""
authors = ["Dawson Booth <pypi@dawsonbooth.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/dawsonbooth/PACKAGE_NAME"
repository = "https://github.com/dawsonbooth/PACKAGE_NAME"
keywords = []
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE",
]
packages = [
    { include = "MODULE_NAME" },
]

[tool.poetry.scripts]
PACKAGE_NAME = 'MODULE_NAME.__main__:main'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
rope = "^0.18.0"
mkdocs = "^1.1.2"
pydoc-markdown = "^3.9.0"
invoke = "^1.5.0"
pyclean = "^2.0.0"
black = "^20.8b1"
flake8 = "^3.8.4"
mypy = "^0.790"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
